name: mobile_programing
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  win32: ^5.1.2
  flutter_animate: ^3.1.0
  simple_animations: ^5.0.2
  geolocator: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/login.png
    - assets/images/profile.jpg
    - assets/images/user.png
    - assets/images/wallet.png
    - assets/images/settings.png
    - assets/images/history.png
    - assets/images/bank.png
    - assets/images/success.png
    - assets/images/cancel.png
